pipeline {
    agent any

    tools {
        maven 'maven'
        jdk 'java-11'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'devsecops', url: 'https://github.com/ManojKRISHNAPPA/Project-movie-app.git'
            }
        }

        stage('Compile') {
            steps {
                sh 'mvn compile'
            }
        }

        stage('Unit Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }

    post {
        always {
            // Publish JUnit test results if they exist
            junit '**/target/surefire-reports/*.xml'
        }
    }
}
